// <auto-generated />
namespace MobileShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateFooter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateFooter));
        
        string IMigrationMetadata.Id
        {
            get { return "201707160312261_updateFooter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
