// <auto-generated />
namespace MobileShop.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddIEnumerableForProduct_Post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddIEnumerableForProduct_Post));
        
        string IMigrationMetadata.Id
        {
            get { return "201706250756388_AddIEnumerableForProduct_Post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
